image:
  file: .gitpod.Dockerfile
tasks:
  - init: sh recompile.sh
vscode:
  extensions:
    - thiagoabreu.vala@0.3.5:wpqKL9G/pGRsFlLDBLF2hA==
    - asabil.meson@1.2.0:sYg01j3Mm+6RJtaIRwyR5A==

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser